name: Playwright Tests

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
    - name: Conda Init & Initialize Playwright Env
      run: |
        . ~/.bashrc
        conda activate playwright
    