name: Playwright Tests

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
    - name: Conda Init
      run: |
        conda init bash
        source ~/.bash_profile
    - name: Find Playwright
      run: |
        stat /Users/sseibert/miniconda3/envs/playwright/bin/playwright
    - name: Run Tests
      run: |
        /Users/sseibert/miniconda3/envs/playwright/bin/playwright install
        /Users/sseibert/miniconda3/envs/playwright/bin/python -m pytest -sv nbclassic/tests/end_to_end