name: Playwright Tests

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
    - name: Conda Init
      run: |
        conda init bash
        source ~/.bash_profile
    - name: Create Conda Env
      run: |
        conda create -n playwright -y -c conda-forge python=3.9.12 nodejs 
    - name: Activate Conda Env
      run: |
        /Users/sseibert/miniconda3/bin/activate playwright 
        conda info --envs 
