name: Playwright Tests

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
    - name: Step 1
      run: |
        whoami
    - name: Step 2
      run: |
        which python
    - name: Step 3
      run: |
        which python3
    - name: Step 4
      run: |
        which conda